import { Pool } from 'pg'
import dotenv from 'dotenv'

dotenv.config({ path: 'backend/.env' })

async function check() {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL })
  // Names of products I attempted to add in Batches 2-6 (237 products)
  const batch2Names = ['Blanc Kogane', 'Armani Privé Vert Malachite', 'My Way Le Parfum', 'Acqua di Giò Parfum (2023)', 'Armani Privé Rouge Malachite', 'The Yulong (Armani Privé)', 'Armani Privé Rose Milano', 'Armani Privé Jasmin Kusamono', 'Armani Privé Gardénia Antigua', 'Armani Privé Pivoine Suzhou', 'Armani Privé Figuier Eden', 'Armani Privé Vétiver d\'Hiver', 'Armani Privé Cèdre Sambac', 'Armani Privé Orangerie Venise', 'Armani Privé Thé Yulong', 'Armani Privé Santal Dān Shā', 'Armani Code (EDP 2021)', 'Armani Code Parfum (2022)', 'Stronger With You Absolutely', 'Stronger With You Only', 'Sì Intense (2023)', 'Sì Passione Éclat', 'My Way Floral', 'My Way Intense', 'Acqua di Gioia Jasmine', 'Terra di Gioia', 'Ocean di Gioia', 'Sky di Gioia', 'YSL Myself (EDP)', 'YSL Libre L\'Absolu Platine', 'YSL Black Opium Over Red', 'YSL Black Opium Illicit Green', 'YSL Mon Paris Lumière', 'YSL Libre Le Parfum', 'YSL Y Elixir', 'YSL L\'Homme Le Parfum', 'YSL La Nuit de L\'Homme Bleu Électrique', 'YSL Y Eau de Toilette (2022)', 'YSL Babycat (Vestiaire des Parfums)', 'YSL Tuxedo (Vestiaire des Parfums)', 'YSL Caban (Vestiaire des Parfums)', 'YSL Caftan (Vestiaire des Parfums)', 'YSL Saharienne (Vestiaire des Parfums)', 'YSL Blouse (Vestiaire des Parfums)', 'YSL Grain de Poudre (Vestiaire des Parfums)', 'Armani Privé Cuir Zerzura', 'Armani Privé Oud Royal', 'Armani Privé Musc Shamal', 'Armani Privé Ambre Orient', 'Armani Privé Ambre Eccentrico'];
  const batch3Names = ['Armani Privé Rose d\'Arabie', 'Armani Privé Cuir Améthyste', 'Armani Privé Myrrhe Impériale', 'Armani Privé Encens Satin', 'Armani Privé Sable Nuit', 'Armani Privé Magenta Tanzanite', 'Armani Privé Indigo Tanzanite', 'Armani Privé Blanc Kogane', 'Armani Privé Noir Kogane', 'Sì Passione (Giorgio Armani)', 'Sì Fiori (Giorgio Armani)', 'In Love with You (Giorgio Armani)', 'Stronger with You Freeze', 'Emporio Armani Because It\'s You', 'Acqua di Gió Profondo Lights', 'Acqua di Gió Absolu', 'Armani Code Ultimage', 'Armani Code Absolu', 'Armani Mania for Men (Discontinued)', 'YSL Elle (EDP)', 'YSL Cinema (EDP)', 'YSL In Love Again', 'YSL Manifesto (EDP)', 'YSL Black Opium Nuit Blanche', 'YSL Black Opium Floral Shock', 'YSL Black Opium Neon', 'YSL Black Opium Extreme', 'YSL Libre Eau de Toilette', 'YSL Y Live', 'YSL L\'Homme Libre', 'YSL L\'Homme Ultime', 'YSL L\'Homme Cologne Bleue', 'YSL La Nuit de l\'Homme L\'Intense', 'YSL La Nuit de l\'Homme Frozen Cologne', 'YSL Opium (2009 Edition)', 'Dior Addict (EDP)', 'Dior Hypnotic Poison (EDT)', 'Dior Pure Poison (EDP)', 'Dior Dune (EDT)', 'Dior Dolce Vita (EDT)', 'Dior Eden-Roc', 'Dior Vanilla Diorama', 'Dior Gris Dior', 'Dior Ambre Nuit', 'Dior Bois d\'Argent', 'Dior Sakura', 'Dior Lucky', 'Dior La Colle Noire', 'Dior Rose Gipsy', 'Dior Oud Bouquet'];
  const batch4Names = ['J\'Adore l\'Or (2023 Edition)', 'J\'Adore Parfum d\'Eau', 'Dior Homme Intense (2011)', 'Dior Homme Parfum (2014)', 'Dior Homme Original (With Iris)', 'Dior Fahrenheit Le Parfum', 'Poison Girl (EDP)', 'Dior Joy (EDP)', 'Dior Joy Intense', 'Miss Dior Rose N\'Roses', 'Miss Dior Absolutely Blooming', 'Midnight Poison (Discontinued)', 'D&G Anthology L\'Imperatrice 3', 'D&G Pour Femme Intense', 'Dolce (D&G)', 'Dolce Garden (D&G)', 'Dolce Shine (D&G)', 'Dolce Lily (D&G)', 'The One Desire (D&G)', 'The One Gold (D&G)', 'The One For Men Eau de Parfum Intense', 'Light Blue Intense Pour Homme', 'Light Blue Forever Pour Homme', 'Light Blue Italian Love Pour Homme', 'Light Blue Summer Vibes Pour Homme', 'K by Dolce & Gabbana (EDP)', 'Q by Dolce & Gabbana (EDP)', 'Gucci Flora Gorgeous Gardenia', 'Gucci Flora Gorgeous Jasmine', 'Gucci Flora Gorgeous Magnolia', 'Gucci Bloom (EDP)', 'Gucci Bloom Ambrosia di Fiori', 'Gucci Bloom Profumo di Fiori', 'Gucci Guilty Pour Femme (EDP)', 'Gucci Guilty Black Pour Homme', 'Gucci Guilty Absolute Pour Homme', 'Gucci Memoire d\'une Odeur', 'Givenchy L\'Interdit (EDP)', 'Givenchy L\'Interdit Rouge', 'Givenchy Gentleman (EDP)', 'Givenchy Gentleman Reserve Privée', 'Givenchy Pi (EDT)', 'Givenchy Amarige (EDT)', 'Givenchy Organza (EDP)', 'Valentino Valentina (EDP)', 'Valentino Voce Viva', 'Valentino Voce Viva Intensa', 'Valentino Donna Born in Roma Coral Fantasy', 'Valentino Uomo Born in Roma Yellow Dream', 'Black Phantom (Memento Mori)'];
  const batch5Names = ['Armani Sì (EDP)', 'Armani Sì Passione', 'Armani My Way (EDP)', 'Acqua di Gioia (EDP)', 'Armani Code Pour Homme (EDT)', 'YSL Black Opium (EDP)', 'YSL Black Opium Le Parfum', 'YSL Mon Paris (EDP)', 'Guerlain L’Homme Idéal (EDP)', 'Guerlain La Petite Robe Noire', 'Guerlain Shalimar (EDP)', 'Guerlain Habit Rouge (EDT)', 'Jean Paul Gaultier Scandal Pour Homme', 'Jean Paul Gaultier Scandal (Woman)', 'JPG Divine (EDP)', 'JPG La Belle (EDP)', 'D&G The Only One', 'D&G Pour Femme', 'Chanel Allure Sensuelle', 'Chanel No. 5 (EDP)', 'Bvlgari Tygar', 'Bvlgari Aqva Pour Homme', 'Bvlgari Goldea (EDP)', 'Kilian Love Don’t Be Shy', 'Bond No. 9 New York Nights', 'Zene (The Art of Love)', 'Nishane Hacivat (EDP)', 'Nishane Ani (EDP)', 'Nishane Hundred Silent Ways', 'Tom Ford Sole di Positano', 'Tom Ford Tuscan Leather', 'Tom Ford Ombré Leather (EDP)', 'Jean Paul Gaultier Le Beau', 'Mancera Paris Roses Vanille', 'Mancera Red Tobacco', 'Mancera Instant Crush', 'Mancera Cedrat Boise', 'Club de Nuit Intense Man (EDT)', 'Sauvage (EDT)', 'Sauvage Elixir', 'Dolce & Gabbana Light Blue Pour Homme', 'Bleu de Chanel (EDP)', 'Acqua di Gio (EDT)', 'Acqua di Gio Profondo', 'YSL Y Eau de Parfum', 'YSL Y Le Parfum', 'Lattafa Asad (أسد)', 'Prada Luna Rossa Ocean (EDP)', 'Paco Rabanne Invictus Victory', 'Paco Rabanne Phantom (EDT)'];
  const batch6Names = ['Carolina Herrera 212 VIP Rose', 'Carolina Herrera Good Girl Blush', 'Versace Eros (EDT)', 'Versace Eros Pour Femme (EDP)', 'Versace Bright Crystal (EDT)', 'Versace Bright Crystal Absolu', 'Versace Crystal Noir (EDP)', 'Valentino Born in Roma Intense (Uomo)', 'Valentino Born in Roma Yellow Dream', 'Jean Paul Gaultier Le Male', 'D&G The One for Man (EDT)', 'Roja Parfums Apex (EDP)', 'Parfums de Marly Carlisle (EDP)', 'Parfums de Marly Oriana', 'Parfums de Marly Valaya', 'Maison Margiela Beach Walk', 'Sauvage (Parfum)', 'Dior Home Sport (2021 Version)', 'Dior Homme (2020 Version)', 'Dior Fahrenheit (EDT)', 'Oud Ispahan', 'Miss Dior (EDP 2021)', 'J\'adore (EDP)', 'Sauvage (EDP)', 'Sauvage (Eau Forte)', 'Armani Stronger With You (EDT)', 'Gucci Guilty Elixir Pour Homme', 'Oud G', 'Prada Luna Rossa Black', 'L\'Homme Ideal Platine Prive', 'Burberry Weekend for Men', 'Lacoste Red (Style in Play)', 'Bad Boy (EDT)', 'Invictus (EDT)', 'Boss Bottled Night', 'Montblanc Explorer', 'Montblanc Legend (EDT)'];

  const allNames = [...batch2Names, ...batch3Names, ...batch4Names, ...batch5Names, ...batch6Names]
  
  try {
    const missingInDb = []
    for (const name of allNames) {
        const res = await pool.query('SELECT id FROM products WHERE name = $1', [name])
        if (res.rows.length === 0) {
            missingInDb.push(name)
        }
    }
    console.log('MISSING_FROM_TURNS_2_TO_6:', JSON.stringify(missingInDb))
  } catch (err) {
    console.error('Error:', err)
  } finally {
    await pool.end()
  }
}

check()
